Added example to inference PaliGemma on Android using HF & Gradio Cli…
google-gemma/cookbook pull request #39
Opened 2024-08-16 05:20 UTC by NSTiwari

Added example to inference PaliGemma on Android using HF & Gradio Client for tasks such as image captioning, visual question-answering, and zero-shot object detection. Please review.

2024-08-19 03:39 UTC, windmaple requested changes

2024-08-19 03:39 UTC, windmaple commented on PaliGemma/PaliGemma-on-Android/Python_Server/README.md
> +6. create a folder `images` in the `/media` folder
there is no 'media' folder

2024-08-19 03:39 UTC, windmaple commented on PaliGemma/PaliGemma-on-Android/Python_Server/README.md
> +4. execute command `python manage.py migrate` for setting up the database
I'm getting:

    ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS").split(" ")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

2024-08-19 03:39 UTC, windmaple commented on PaliGemma/PaliGemma-on-Android/Python_Server/README.md
> +6. create a folder `images` in the `/media` folder
step 7 and 8 should really just be 'mkdir -p apiserver/media/images'

2024-08-19 03:39 UTC, windmaple commented on PaliGemma/PaliGemma-on-Android/Python_Server/README.md
> +4. execute command `python manage.py migrate` for setting up the database
I had to set it to 'localhost' to get past this

2024-08-19 03:39 UTC, windmaple commented on PaliGemma/PaliGemma-on-Android/Python_Server/README.md
> +8. go to url [http://127.0.0.1:8000/api/docs#/default/api_views_detect](http://127.0.0.1:8000/api/docs#/default/api_views_detect) to test the api
I'm getting:

raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")

After export SECRET_KEY='*', I get a '400' error.

2024-08-19 03:45 UTC, NSTiwari commented on PaliGemma/PaliGemma-on-Android/Python_Server/README.md
> +8. go to url [http://127.0.0.1:8000/api/docs#/default/api_views_detect](http://127.0.0.1:8000/api/docs#/default/api_views_detect) to test the api
Hi @windmaple,
Yes, that's because the Python server is hosted on Render, so the settings are configured in such a way that they can be directly handled from Render UI instead of hardcoding in the Python file.

2024-08-19 04:58 UTC, windmaple commented on PaliGemma/PaliGemma-on-Android/README.md
> +# PaliGemma Android HF
would you like to add your name and social handle here?

2024-08-19 05:23 UTC, NSTiwari commented on PaliGemma/PaliGemma-on-Android/README.md
> +# PaliGemma Android HF
Oh, yes. I'll add it and push the commit. Thank you.

2024-08-19 05:50 UTC, NSTiwari commented on PaliGemma/PaliGemma-on-Android/README.md
> +# PaliGemma Android HF
@windmaple: Added the social links. :)

2024-08-21 12:15 UTC, NSTiwari reviewed
@windmaple: Since the Python server is hosted (in production), changes in the configs would cause a conflict.

Could you please review? The APK and the Android code can be readily used though.

2024-08-22 08:17 UTC, windmaple commented on PaliGemma/PaliGemma-on-Android/Python_Server/README.md
> +8. go to url [http://127.0.0.1:8000/api/docs#/default/api_views_detect](http://127.0.0.1:8000/api/docs#/default/api_views_detect) to test the api
OK. Can you add this info in the README just in case https://paligemma.onrender.com goes down (hopefully never) or somebody wants to host the service by themselves?

2024-08-22 09:28 UTC, NSTiwari commented on PaliGemma/PaliGemma-on-Android/Python_Server/README.md
> +8. go to url [http://127.0.0.1:8000/api/docs#/default/api_views_detect](http://127.0.0.1:8000/api/docs#/default/api_views_detect) to test the api
> OK. Can you add this info in the README just in case https://paligemma.onrender.com goes down (hopefully never) or somebody wants to host the service by themselves?

Added the info!

2024-08-24 00:49 UTC, windmaple approved these changes

2024-08-24 00:49 UTC, merged