Llamafile - Gemma 2 Colab Notebook
google-gemma/cookbook pull request #50
Opened 2024-09-23 04:06 UTC by kinarr

This demonstrates how to use Llamafile with Gemma 2

2024-09-23 05:18 UTC, windmaple commented
Can you add an entry in the table of contents in README?

2024-09-23 08:44 UTC, kinarr commented
> Can you add an entry in the table of contents in README?

Added it now and also removed the entry from the WISHLIST

2024-09-23 12:20 UTC, windmaple requested changes

2024-09-23 12:20 UTC, windmaple commented on README.md
> +| [Using_Gemma_with_Llamafile.ipynb](Gemma/Using_Gemma_with_Llamafile.ipynb)                                                                       | An example to demonstrate using Gemma with [Llamaf
Move this up to below Run_with_Ollma.ipynb. This position is for RAG.

2024-09-23 14:15 UTC, kinarr commented on README.md
> +| [Using_Gemma_with_Llamafile.ipynb](Gemma/Using_Gemma_with_Llamafile.ipynb)                                                                       | An example to demonstrate using Gemma with [Llamaf
Done.

2024-09-24 00:29 UTC, windmaple approved these changes

2024-09-24 00:30 UTC, merged